title: Vladimir Almaev
description: My personal blog about software development
author: Vladimir Almaev
gravatar-hash: 1109dfea11862164a1d3183b100a3d58 
github-username: valmaev
stackoverflow-id: 1178734
markdown: redcarpet