# blog settings
title: Vladimir Almaev's blog
description: Fail fast and keep discovering
author: Vladimir Almaev
url: https://valmaev.github.io
github-repo-url: https://github.com/valmaev/valmaev.github.io
enforce-ssl: true

# socials
gravatar-hash: 1109dfea11862164a1d3183b100a3d58 
github-username: valmaev
stackexchange-id: 1209981

# jekyll settings
markdown: redcarpet
paginate: 10
exclude: ["README.md"]
gems:
    - jekyll-sitemap