# blog settings
title: Vladimir Almaev's blog
description: Fail fast and keep discovering
url: https://valmaev.github.io
production_host: valmaev.github.io
github_repo_url: https://github.com/valmaev/valmaev.github.io
enforce_ssl: true

# author
author:
    name: Vladimir Almaev
    gravatar_hash: 1109dfea11862164a1d3183b100a3d58 
    github_username: valmaev
    stackexchange_id: 1209981

#analytics
google_analytics_tracking_id: UA-56500618-1

# jekyll settings
markdown: redcarpet
paginate: 10
exclude: ["README.md"]
gems:
    - jekyll-sitemap